# Generated by Django 3.2.6 on 2021-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_id',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'SLEEP'), (3, 'INACTIVE')], default=1),
        ),
    ]
